/* AUTO-GENERATED by scripts/generate-theme-vars.js - DO NOT EDIT */
export const lightThemeVars: Record<string, string> = {
  "--color-primary": "67 132 255",
  "--color-on-primary": "255 255 255",
  "--color-bg": "241 242 244",
  "--color-surface-1": "244 245 247",
  "--color-surface-2": "255 255 255",
  "--color-surface-hover-1": "230 232 235",
  "--color-surface-hover-2": "237 238 241",
  "--color-text": "43 46 50",
  "--color-headline": "20 22 26",
  "--color-muted": "111 114 119",
  "--color-border": "171 174 180",
  "--color-divider": "227 228 231",
  "--color-success": "16 175 95",
  "--color-warning": "230 145 0",
  "--color-error": "215 50 60",
  "--color-info": "67 132 255"
} as const;
export const darkThemeVars: Record<string, string> = {
  "--color-primary": "185 216 255",
  "--color-on-primary": "0 10 20",
  "--color-bg": "10 11 13",
  "--color-surface-1": "25 27 29",
  "--color-surface-2": "39 41 44",
  "--color-surface-hover-1": "49 51 54",
  "--color-surface-hover-2": "64 66 70",
  "--color-text": "213 215 219",
  "--color-headline": "237 238 241",
  "--color-muted": "140 143 149",
  "--color-border": "56 59 63",
  "--color-divider": "21 22 24",
  "--color-success": "16 220 120",
  "--color-warning": "255 180 30",
  "--color-error": "255 70 90",
  "--color-info": "185 216 255"
} as const;

export const getThemeVars = (scheme: 'light' | 'dark') => (scheme === 'dark' ? darkThemeVars : lightThemeVars);
